language: python
python:
  - "3.3"
  - "3.4"
before_install:
  - wget https://github.com/google/protobuf/releases/download/v2.6.1/protobuf-2.6.1.tar.gz
  - tar -xzvf protobuf-2.6.1.tar.gz
  - cd protobuf-2.6.1 && ./configure --prefix=/usr && make && make install
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then travis_retry pip install enum34; fi
script:
  - nosetests
