language: python
python:
  - "3.3"
  - "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y protobuf-compiler
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then travis_retry pip install enum34; fi
script:
  - nosetests
